import { onRequest } from "firebase-functions/v2/https";
import axios from "axios";
require("firebase-functions/logger/compat");


export const generateWords = onRequest(
  { secrets: ["OPENAI_API_KEY"], cors: true }, async (req, res) => {
    try {
      // Extract input data from the request body
      const { input, systemPrompt, cursorPos } = req.body;

      if (!input || !systemPrompt || cursorPos === undefined) {
        res.status(400).json({ error: "Missing required parameters" });
        return;
      }

      // Extract prefix and suffix
      const prefix = input.substring(0, cursorPos);
      const suffix = input.substring(cursorPos);

      // Replace placeholders in the system prompt
      let newSystemPrompt = systemPrompt.replaceAll("[input_prefix]", prefix);
      newSystemPrompt = newSystemPrompt.replaceAll("[input_suffix]", suffix);

      // Call OpenAI API
      const response = await axios.post(
        "https://api.openai.com/v1/chat/completions",
        {
          model: "gpt-3.5-turbo",
          messages: [{ role: "system", content: newSystemPrompt }],
          temperature: 0.7,
        },
        {
          headers: {
            Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
            "Content-Type": "application/json",
          },
        }
      );

      const generatedText = response.data.choices[0]?.message?.content || "";

      if (!generatedText) {
        throw new Error("No words were generated by the API.");
      }

      res.json({ generatedText });
      return;
    } catch (error: any) {
      console.error("Error generating words:", error);
      res.status(500).json({ error: error.message });
      return;
    }
  }
);
