import OpenAI from "openai";

const openai = new OpenAI({apiKey: process.env.REACT_APP_OPENAI_API_KEY, dangerouslyAllowBrowser: true});

export const generateWords2 = async (input: string, systemPrompt: string) => {
  try {
    const newSystemPrompt = systemPrompt.replaceAll("[input]", input);
    const completion = await openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: newSystemPrompt
        }
      ],
      model: "gpt-4o",
      temperature: 0.7,
    });

    const generatedText = completion.choices[0].message.content;
    if (generatedText) {
      return generatedText;
    } else {
      throw new Error("No words were generated by the API.");
    }
  } catch (error) {
    console.error("Error generating words:", error);
    return "";
  }
}