import OpenAI from "openai";

const openai = new OpenAI({apiKey: process.env.REACT_APP_OPENAI_API_KEY, dangerouslyAllowBrowser: true});

export const generateWords = async (input: string, systemPrompt: string, cursorPos: number) => {
  try {
    const prefix = input.substring(0, cursorPos);
    console.log(prefix);
    const suffix = input.substring(cursorPos);
    console.log(suffix);
    let newSystemPrompt = systemPrompt.replaceAll("[input_prefix]", prefix);
    newSystemPrompt = newSystemPrompt.replaceAll("[input_suffix]", suffix);
    console.log(newSystemPrompt);
    const completion = await openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: newSystemPrompt
        }
      ],
      model: "gpt-4o",
      temperature: 0.7,
    });

    const generatedText = completion.choices[0].message.content;
    if (generatedText) {
      return generatedText;
    } else {
      throw new Error("No words were generated by the API.");
    }
  } catch (error) {
    console.error("Error generating words:", error);
    return "";
  }
}